l1 = ["Vandan Patel",20012011130,19,"CE",]
print("List")
print(l1)
l1.insert(1,'Hello')
print("Insert Value")
print(l1)
l1.remove("CE")
print("remove")
print(l1)
l1.append("code")
print("append")
print(l1)
l1.extend("india")
print("Extend")
print(l1)
l1[3]="Computer Eng."
print("Update value")
print(l1)